### ISSUE TITLE
An error "Error using mskoptimset" occurs inside quadprog 

### ISSUE THREAD

**Issue by liliya201104** [HiroIshida/robust-tube-mpc#10]
Error using mskoptimset (line 67)
Expected argument 2 to be a string parameter name or an options structure
created with mskoptimset.

Error in quadprog (line 78)
options          = mskoptimset(defaultopt,options);

Error in OptimalControler/solve (line 76)
                [var_optim, ~, exitflag] = quadprog(obj.H, [], C_ineq1_relaxed, C_ineq2, C_eq1, C_eq2, [], [], [], options);

Error in ModelPredictiveControl/solve (line 21)
            [x_nominal_seq, u_nominal_seq] = obj.optcon.solve();

Error in example_MPC (line 27)
    u_next = mpc.solve(x);

Do you know how I can solve this problem? Thank you very much!

**Comment by HiroIshida** [comment]
Currently I cannot access to matlab, but I geuss the reason. After googling, I found that `mskoptimset` is provided by `MOSEK` optimization solver.  And MOSEK is a third-party libraries. So probably you at some moment installed this software and, because of this,  `quadprog` that is originally provided by MATLAB is overwritten by the MOSEK's one. So probably, removing `MOSEK` or tweaking some setting of MOSEK side will fix the problem. 

this website https://docs.mosek.com/9.2/toolbox/install-interface.html might be helpful.

Please tell me, if you can fix by that.

**Comment by liliya201104** [comment]
Thank you very much for your answer, which is very helpful for me. After removing the MOSEK, the code can work now. Finally, thank you for proving this code, and it is vey helpful for my study.

**Comment by loser-why** [comment]
I have also met this issue. It is the truth that this issue is caused by overloading 'quadprog' function in mosek. Actually, one don't have to delate mosek package. An alternative  solution is to only delete the search path '<MSKHOME>/mosek/9.2/toolbox/r2015a' in matlab. Then, this bug will disappear. At last, I am appreciated to author for providing code. It's a good study material.

**Comment by HiroIshida** [comment]
@loser-why thanks for reporting that!
